// Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ · 微信 zhuatech / zhuatech2
/** 业务表单与列表字段；界面配置不替代后端权限和状态校验。官网 https://www.zhuatech.cn/；微信 zhuatech / zhuatech2。 */
export const fields = {
  shipments: [
    ["customerId", "托运客户", "Customer", "customers", true],
    ["origin", "装货地址", "Pickup address", "text", true],
    ["destination", "卸货地址", "Delivery address", "text", true],
    ["consignee", "收货人", "Consignee", "text", true],
    ["consigneePhone", "收货电话", "Consignee phone", "text"],
    ["goods", "货物说明", "Goods", "text", true],
    ["pieces", "件数", "Pieces", "number", true],
    ["weightKg", "重量 kg", "Weight kg", "decimal", true],
    ["volumeM3", "体积 m³", "Volume m³", "decimal", true],
  ],
  trips: [
    ["carrierId", "承运商", "Carrier", "carriers", true],
    ["driverId", "司机", "Driver", "drivers", true],
    ["vehicleId", "车辆", "Vehicle", "vehicles", true],
    [
      "plannedStartLocal",
      "计划发车",
      "Planned departure",
      "datetime-local",
      true,
    ],
    ["plannedEndLocal", "计划结束", "Planned finish", "datetime-local", true],
    ["carrierFee", "约定运费", "Agreed carrier fee", "decimal", true],
    ["note", "调度备注", "Dispatch note", "textarea"],
  ],
  customers: [
    ["code", "客户编号", "Customer code", "text", true],
    ["name", "客户名称", "Customer name", "text", true],
    ["accountId", "门户账号", "Portal account", "users"],
    ["contact", "联系人", "Contact", "text"],
    ["phone", "电话", "Phone", "text"],
    ["address", "地址", "Address", "text"],
    ["departmentId", "运营部门", "Department", "departments", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  carriers: [
    ["code", "承运商编号", "Carrier code", "text", true],
    ["name", "名称", "Name", "text", true],
    ["contact", "联系人", "Contact", "text"],
    ["phone", "电话", "Phone", "text"],
    ["departmentId", "运营部门", "Department", "departments", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  drivers: [
    ["code", "司机编号", "Driver code", "text", true],
    ["name", "司机姓名", "Driver name", "text", true],
    ["accountId", "登录账号", "Login account", "users", true],
    ["carrierId", "承运商", "Carrier", "carriers", true],
    ["phone", "电话", "Phone", "text"],
    ["licenseNumber", "驾驶证编号", "Licence reference", "text"],
    ["licenseExpires", "有效截止日期", "Valid until", "date"],
    ["departmentId", "运营部门", "Department", "departments", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  vehicles: [
    ["code", "车牌 / 编号", "Plate / code", "text", true],
    ["name", "车辆名称", "Vehicle name", "text", true],
    ["carrierId", "承运商", "Carrier", "carriers", true],
    ["maxWeightKg", "最大重量 kg", "Weight capacity kg", "decimal", true],
    ["maxVolumeM3", "最大体积 m³", "Volume capacity m³", "decimal", true],
    ["maxPieces", "最大件数", "Piece capacity", "number", true],
    ["departmentId", "运营部门", "Department", "departments", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  users: [
    ["username", "用户名", "Username", "text", true],
    ["displayName", "显示名称", "Display name", "text", true],
    ["password", "新密码", "New password", "password"],
    ["roleId", "角色", "Role", "roles", true],
    ["departmentId", "运营部门", "Department", "departments", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  roles: [
    ["name", "角色名称", "Role name", "text", true],
    ["scope", "数据范围", "Data scope", "scope", true],
    ["permissions", "业务权限", "Permissions", "permissions", true],
  ],
  departments: [["name", "部门名称", "Department name", "text", true]],
  permissions: [["name", "权限说明", "Permission name", "text", true]],
  menus: [
    ["name", "中文名称", "Chinese label", "text", true],
    ["nameEn", "英文名称", "English label", "text", true],
    ["permissionCode", "接口权限", "Permission", "permissionCode", true],
    ["position", "顺序", "Order", "number", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  dictionaries: [
    ["type", "字典类型", "Dictionary type", "text", true],
    ["code", "字典值", "Code", "text", true],
    ["name", "中文名称", "Chinese label", "text", true],
    ["nameEn", "英文名称", "English label", "text", true],
    ["enabled", "启用", "Enabled", "checkbox"],
  ],
  settings: [
    ["code", "参数", "Setting", "readonly"],
    ["value", "参数值", "Value", "text", true],
  ],
  expenses: [
    ["tripId", "运输车次", "Trip", "activeTrips", true],
    ["type", "费用类型", "Expense type", "expenseType", true],
    ["amount", "实报金额", "Actual amount", "decimal", true],
    ["reference", "凭证编号", "Reference", "text"],
    ["note", "费用说明", "Expense note", "textarea", true],
  ],
  invoices: [
    ["kind", "对账类型", "Settlement type", "invoiceKind", true],
    ["customerId", "客户", "Customer", "customers", true],
    [
      "shipmentIds",
      "已签收运单",
      "Delivered shipments",
      "deliveredShipments",
      true,
    ],
    ["tripId", "已关闭车次", "Closed trip", "closedTrips", true],
    ["dueDate", "到期日", "Due date", "date", true],
  ],
};
/** 列表列围绕真实操作，未知字段不允许任意反射排序。官网 https://www.zhuatech.cn/；微信 zhuatech / zhuatech2。 */
export const columns = {
  shipments: [
    "code",
    "customerName",
    "origin",
    "destination",
    "goods",
    "pieces",
    "freight",
    "status",
  ],
  trips: [
    "code",
    "vehicleName",
    "driverName",
    "plannedStart",
    "plannedEnd",
    "carrierFee",
    "status",
  ],
  expenses: ["id", "tripId", "type", "amount", "createdBy", "status"],
  invoices: ["code", "kind", "partyName", "total", "paid", "dueDate", "status"],
  customers: ["code", "name", "contact", "phone", "enabled"],
  carriers: ["code", "name", "contact", "phone", "enabled"],
  drivers: ["code", "name", "phone", "licenseExpires", "enabled"],
  vehicles: [
    "code",
    "name",
    "maxWeightKg",
    "maxVolumeM3",
    "maxPieces",
    "enabled",
  ],
  users: ["username", "displayName", "roleId", "departmentId", "enabled"],
  roles: ["name", "scope", "permissions"],
  departments: ["id", "name"],
  permissions: ["code", "name"],
  menus: ["code", "name", "permissionCode", "position", "enabled"],
  dictionaries: ["type", "code", "name", "enabled"],
  settings: ["code", "value"],
  audit: ["id", "actor", "action", "objectId", "createdAt"],
};
export const labels = {
  id: ["编号", "ID"],
  code: ["单号 / 编号", "Reference"],
  name: ["名称", "Name"],
  customerName: ["客户", "Customer"],
  origin: ["装货", "Pickup"],
  destination: ["卸货", "Delivery"],
  goods: ["货物", "Goods"],
  pieces: ["件数", "Pieces"],
  freight: ["客户运价", "Client freight"],
  status: ["状态", "Status"],
  vehicleName: ["车辆", "Vehicle"],
  driverName: ["司机", "Driver"],
  plannedStart: ["计划发车", "Departure"],
  plannedEnd: ["计划结束", "Finish"],
  carrierFee: ["承运费", "Carrier fee"],
  tripId: ["车次编号", "Trip ID"],
  type: ["类型", "Type"],
  amount: ["金额", "Amount"],
  createdBy: ["填报人", "Submitted by"],
  kind: ["方向", "Direction"],
  partyName: ["对账对象", "Party"],
  total: ["总额", "Total"],
  paid: ["已收 / 付", "Settled"],
  dueDate: ["到期日", "Due date"],
  contact: ["联系人", "Contact"],
  phone: ["电话", "Phone"],
  enabled: ["启用", "Enabled"],
  licenseExpires: ["证件有效至", "Licence expiry"],
  maxWeightKg: ["载重 kg", "Weight kg"],
  maxVolumeM3: ["容积 m³", "Volume m³"],
  maxPieces: ["载件数", "Pieces"],
  username: ["用户名", "Username"],
  displayName: ["显示名称", "Display name"],
  roleId: ["角色", "Role"],
  departmentId: ["部门", "Department"],
  scope: ["范围", "Scope"],
  permissions: ["权限", "Permissions"],
  permissionCode: ["接口权限", "Permission"],
  position: ["顺序", "Order"],
  value: ["参数值", "Value"],
  actor: ["操作人", "Actor"],
  action: ["操作", "Action"],
  objectId: ["对象", "Object"],
  createdAt: ["时间", "Time"],
};
export const statusLabels = {
  RECORDED: ["已记录", "Recorded"],
  RESOLVED: ["已解决", "Resolved"],
  DRAFT: ["草稿", "Draft"],
  READY: ["待配载", "Ready to load"],
  PLANNED: ["已配载", "Loaded"],
  DISPATCHED: ["待接单", "Dispatched"],
  ACCEPTED: ["已接单", "Accepted"],
  IN_TRANSIT: ["运输中", "In transit"],
  POD_PENDING: ["回单待审", "POD review"],
  DELIVERED: ["已签收", "Delivered"],
  CLOSED: ["已关单", "Closed"],
  CANCELLED: ["已取消", "Cancelled"],
  SUBMITTED: ["待复核", "Review pending"],
  APPROVED: ["已核准", "Approved"],
  REJECTED: ["已退回", "Rejected"],
  OPEN: ["待处理", "Open"],
  PARTIAL: ["部分结算", "Part settled"],
  PAID: ["已结清", "Settled"],
  VOID: ["已作废", "Void"],
  RECEIVABLE: ["客户应收", "Receivable"],
  PAYABLE: ["承运应付", "Payable"],
  ALL: ["全部部门", "All departments"],
  DEPARTMENT: ["本部门", "Own department"],
  ASSIGNED: ["本人关联", "Own assignments"],
};
